baseurl = "https://snabbwall.igalia.com/"
languageCode = "en-us"
title = "SnabbWall"
PygmentsCodeFences = true
pygmentsstyle = "tango"

[params]
	themeColor = "theme-base-08"
	description = "L7 flow filtering"

[permalinks]
	news = "/news/:year/:month/:day/:slug"

[[menu.main]]
	identifier = "news"
	name = "News"
	weight = -10
	url = "/news/"
