name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Hugo
        id: cache-hugo
        uses: actions/cache@v2
        with:
          path: ".hugo"
          key: ${{ runner.os }}-hugo-${{ hashFiles('.github/hugo') }}
      - name: Fetch Hugo
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: .github/hugo .hugo
      - name: Build
        run: .hugo/hugo -d public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
